networks:
  dev:

services:


  backend:
    build:
      context: ./backend
   #networks:
      #- dev
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
   # networks:
    #  - dev